version: '3.8'

services:
  library:
    image: ghcr.io/fogo-sh/distributed-library
    build: .
    ports:
      - "127.0.0.1:8000:80"

  frontend:
    image: ghcr.io/fogo-sh/distributed-library-frontend
    build: ./frontend
    ports:
      - "127.0.0.1:7000:80"
