[[actions]]
action_type = 'AddUser'
name = 'jack'
github_username = 'jackharrhy'

[[actions]]
action_type = 'AddUser'
name = 'riley'
github_username = 'nint8835'

[[actions]]
action_type = 'AddBook'
user = 'jack'
book = { id = 'jack-dop', isbn = 9781617298578, url = 'https://www.manning.com/books/data-oriented-programming', cover_image = 'https://images.manning.com/360/480/resize/book/0/76cfc61-95fd-4c0d-b221-0e5c3ca90583/Sharvit-DOP-HI.png' }

[[actions]]
action_type = 'AddBook'
user = 'riley'
book = { id = 'riley-dop', isbn = 9781617298578, url = 'https://www.manning.com/books/data-oriented-programming', cover_image = 'https://images.manning.com/360/480/resize/book/0/76cfc61-95fd-4c0d-b221-0e5c3ca90583/Sharvit-DOP-HI.png' }

[[actions]]
action_type = 'AddBook'
user = 'riley'
book = { id = 'riley-docs-for-devs', isbn = 9781484272169, url = 'https://docsfordevelopers.com/', cover_image = 'https://docsfordevelopers.files.wordpress.com/2021/07/978-1-4842-7216-9.jpg'}

[[actions]]
action_type = 'AddBook'
user = 'riley'
book = { id = 'riley-kubernetes-networking', isbn = 9781492081654, url = 'https://www.oreilly.com/library/view/networking-and-kubernetes/9781492081647/', cover_image = 'https://learning.oreilly.com/library/cover/9781492081647/250w/'}

[[actions]]
action_type = 'AddBook'
user = 'riley'
book = { id = 'riley-mia', isbn = 9781617294457, url = 'https://www.manning.com/books/microservices-in-action', cover_image = 'https://images.manning.com/264/352/resize/book/8/809fab1-8912-4fb7-b39e-f49844525807/Bruce-Microservices-HI.png'}

[[actions]]
action_type = 'AddBook'
user = 'riley'
book = { id = 'riley-msia', isbn = 9781617295959, url = 'https://www.manning.com/books/microservices-security-in-action', cover_image = 'https://images.manning.com/264/352/resize/book/6/4cf7d31-fe33-426f-be39-fda5bfbf4191/Siriwardena-MS-HI.png'}

[[actions]]
action_type = 'AddBook'
user = 'jack'
book = { id = 'jack-eia', isbn = 9781617295027, url = 'https://www.manning.com/books/elixir-in-action-second-edition', cover_image = 'https://images.manning.com/360/480/resize/book/b/860dd1f-9401-4f00-be22-e00ad954be2f/Juric-Elixir-2ed-HI.jpg'}

[[actions]]
action_type = 'AddBook'
user = 'jack'
book = { id = 'jack-pgia', isbn = 9781617296697, url = 'https://www.manning.com/books/postgis-in-action-third-edition', cover_image = 'https://images.manning.com/360/480/resize/book/6/ab6e387-e2fc-4eb9-b7af-ddd6ef96ae4d/Obe-PostGIS-3ed-HI.png'}

[[actions]]
action_type = 'AddBook'
user = 'jack'
book = { id = 'jack-ah', isbn = 9780735211292, url = 'https://jamesclear.com/atomic-habits', cover_image = 'https://jamesclear.com/wp-content/uploads/2022/09/9M-atomic-habits-dots.png'}

[[actions]]
action_type = 'AddBook'
user = 'jack'
book = { id = 'jack-sc', isbn = 9780553380958, url = 'https://www.amazon.ca/Snow-Crash-Novel-Neal-Stephenson/dp/0553380958', cover_image = 'https://m.media-amazon.com/images/I/91NrsGzBjUL.jpg'}

[[actions]]
action_type = 'AddBook'
user = 'jack'
book = { id = 'jack-tia', isbn = 9781617298349, url = 'https://www.manning.com/books/tensorflow-in-action', cover_image = 'https://images.manning.com/360/480/resize/book/a/01d777a-7288-4d90-899b-4a1cccca0cb3/Ganegedara-TF-HI.png'}

[[actions]]
action_type = 'AddUser'
name = 'marty'
github_username = 'lilmert'

[[actions]]
action_type = 'AddBook'
user = 'marty'
book = { id = 'marty-dsaa', isbn = 9781118290279, url = 'https://www.amazon.com/Structures-Algorithms-Python-Michael-Goodrich/dp/1118290275', cover_image = 'https://m.media-amazon.com/images/I/51OLsdBy8WL._SX383_BO1,204,203,200_.jpg' }

[[actions]]
action_type = 'AddBook'
user = 'marty'
book = { id = 'marty-ctci', isbn = 9780984782857, url = 'https://www.crackingthecodinginterview.com/', cover_image = 'https://m.media-amazon.com/images/I/41oYsXjLvZL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg' }

[[actions]]
action_type = 'AddBook'
user = 'marty'
book = { id = 'marty-selbtmt', isbn = 9781736417911, url = 'https://staffeng.com/book', cover_image = 'https://staffeng.com/StaffEngCoverHero.png' }

[[actions]]
action_type = 'AddBook'
user = 'marty'
book = { id = 'marty-unixhist', isbn = 9781695978553, url = 'https://www.amazon.com/UNIX-History-Memoir-Brian-Kernighan/dp/1695978552', cover_image = 'https://m.media-amazon.com/images/I/41yNovYPxKL._SX331_BO1,204,203,200_.jpg' }

[[actions]]
action_type = 'AddBook'
user = 'marty'
book = { id = 'marty-tmux', isbn = 9780735611313, url = 'https://www.goodreads.com/book/show/44882.Code', cover_image = 'https://pragprog.com/titles/bhtmux2/tmux-2/bhtmux2_hu6d5b8b63a4954cb696e89b39f929331b_458570_250x0_resize_q75_box.jpg' }

[[actions]]
action_type = 'AddBook'
user = 'marty'
book = { id = 'marty-cthlochas', isbn = 9780735611313, url = 'https://www.goodreads.com/book/show/44882.Code', cover_image = 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1328830222l/44882.jpg' }

[[actions]]
action_type = 'AddBook'
user = 'marty'
book = { id = 'marty-tcc', isbn = 9780137081073, url = 'https://www.amazon.com/Clean-Coder-Conduct-Professional-Programmers/dp/0137081073', cover_image = 'https://m.media-amazon.com/images/I/51uO-K+V5dL._SX381_BO1,204,203,200_.jpg' }

[[actions]]
action_type = 'AddBook'
user = 'marty'
book = { id = 'marty-dsatcl', isbn = 9781491947852, url = 'https://www.oreilly.com/library/view/data-science-at/9781491947845/', cover_image = 'https://learning.oreilly.com/library/cover/9781491947845/250w/' }
